on:
  workflow_dispatch: null
jobs:
  auto-label:
    name: Auto-label PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f42bc1c9890d4047f6d0ff69e889a4ca # v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch base branch
        run: git fetch origin main

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.6.0
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@b4ffde65f42bc1c9890d4047f6d0ff69e889a4ca # v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4 # v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get affected projects
        id: affected
        run: |
          AFFECTED_PROJECTS=$(pnpm nx print-affected --base=origin/main --head=HEAD --select=projects)
          echo "affected_projects=$AFFECTED_PROJECTS" >> $GITHUB_OUTPUT

      - name: Label based on affected projects
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const affectedProjects = process.env.AFFECTED_PROJECTS.split(',').map(p => p.trim());
            const labels = new Set();

            if (affectedProjects.includes('api')) {
              labels.add('api');
            }
            if (affectedProjects.some(p => p.startsWith('frontend-'))) {
              labels.add('frontend');
            }
            if (affectedProjects.some(p => p.startsWith('cloud-functions/'))) {
              labels.add('cloud-function');
            }
            if (affectedProjects.some(p => p.startsWith('libs/'))) {
              labels.add('library');
            }
            if (affectedProjects.some(p => p.startsWith('infra/'))) {
              labels.add('infrastructure');
            }

            if (labels.size > 0) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: Array.from(labels)
              });
            }
