name: PR Integration Validation
permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  validate:
    name: Validate PR Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f42bc1c9890d4047f6d0ff69e889a4ca # v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@4fe8674f344d65cf7384fc21ba97c2b05fd8df75 # v4.1.0
        with:
          version: 10.0.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@b4ffde65f42bc1c9890d4047f6d0ff69e889a4ca # v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4 # v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm nx affected --target=lint --parallel=3 --parallel=3

      - name: Run Build
        run: pnpm nx affected --target=build --parallel=3 --parallel=3

      - name: Run Tests
        run: pnpm nx affected --target=test --parallel=3 --parallel=2 --max-workers=2

      - name: Validate TypeScript
        run: |
          pnpm tsc --noEmit

      - name: Generate PR Summary
        run: |
          echo "## Integration Validation Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Lint:** Passed" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Build:** Passed" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Tests:** Passed" >> $GITHUB_STEP_SUMMARY
          echo "✅ **TypeScript Validation:** Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This PR successfully integrates changes from PRs #45, #46, and #47, along with TypeScript error fixes." >> $GITHUB_STEP_SUMMARY
