review:
  # Bot name used in PR comments
  name: CodeRabbit

  # Priority of files to focus on
  file_priorities:
    # High priority files
    - libs/adk/src/services/**/*.ts
    - libs/adk/src/utilities/**/*.ts
    - libs/adk/src/interfaces/**/*.ts
    - libs/adk/src/types/**/*.ts
    - apps/agents/src/**/*.ts
    - libs/utils/gcp-auth*/src/**/*.ts

  # Files to ignore
  ignore:
    - '**/*.spec.ts'
    - '**/*.test.ts'
    - '**/*.d.ts'
    - '**/node_modules/**'
    - '**/.next/**'
    - '**/dist/**'

  # Review settings
  review_comment_settings:
    collapse_walkthrough: true
    auto_collapse_paths:
      - node_modules/
      - dist/
      - build/
    auto_collapse_generated: true

  # Advanced settings
  request_review_on_push: true
  request_changes_per_pr: 30
  enable_pending_status: true
  notification_settings:
    notify_on_error: true

# AI model settings
ai:
  auto_review: true
  review_simple_changes: true
  review_summary: true
  summarize_pull_request: true
  line_comments: true
  semantic_search: true

  # Focus areas
  focus:
    - type_safety
    - error_handling
    - security
    - performance
    - best_practices
    - documentation
