name: Copilot Agent Configuration

# Configure allowed connections for the Copilot coding agent
# For comprehensive project instructions, refer to the agents.md file at the root of the repository
allowlist:
  # Allow connections to Nx Cloud services for distributed execution and caching
  hosts:
    - 'cloud.nx.app'
    - 'nx.app'
    - '*.nx.app'
