# Modern Cloud Build configuration
# Optimized for containerization and deployment
# Integrates with GitHub Actions CI/CD pipeline

substitutions:
  _ARTIFACT_REGISTRY: 'asia-southeast1-docker.pkg.dev'
  _GCP_REGION: 'asia-southeast1'
  _DULCE_AGENTS_TOPIC: 'dulce.agents'
  _DULCE_AGENT_RUNS_TABLE: 'dulce_agent_runs'

steps:
  #