# Optimized Cloud Build configuration
# Focuses on containerization and deployment only
# CI tasks are handled by GitHub Actions

steps:
  # Build and push container images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-agent-runner'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/dulce/agent-runner:${_GITHUB_SHA}'
      - '-f'
      - 'apps/agents/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/dulce/api:${_GITHUB_SHA}'
      - '-f'
      - 'apps/api/Dockerfile'
      - '.'

  # Security scan containers
  - name: 'aquasec/trivy:latest'
    id: 'scan-agent-runner'
    args: 
      - 'image'
      - '--exit-code'
      - '1'
      - '--severity'
      - 'HIGH,CRITICAL'
      - '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/dulce/agent-runner:${_GITHUB_SHA}'

  - name: 'aquasec/trivy:latest'
    id: 'scan-api'
    args: 
      - 'image'
      - '--exit-code'
      - '1'
      - '--severity'
      - 'HIGH,CRITICAL'
      - '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/dulce/api:${_GITHUB_SHA}'

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-agent-runner'
    args: ['push', '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/dulce/agent-runner:${_GITHUB_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args: ['push', '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/dulce/api:${_GITHUB_SHA}']

  # Deploy services
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-function'
    args:
      - 'functions'
      - 'deploy'
      - 'event-parser'
      - '--project=${PROJECT_ID}'
      - '--region=${_GCP_REGION}'
      - '--trigger-topic=dulce.agents'
      - '--runtime=nodejs20'
      - '--source=apps/event-parser'
      - '--entry-point=parseAgentEvent'
      - '--service-account=event-parser-sa@${PROJECT_ID}.iam.gserviceaccount.com'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-agent-runner'
    args:
      - 'run'
      - 'deploy'
      - 'agent-runner'
      - '--project=${PROJECT_ID}'
      - '--region=${_GCP_REGION}'
      - '--image=${_ARTIFACT_REGISTRY}/${PROJECT_ID}/dulce/agent-runner:${_GITHUB_SHA}'
      - '--platform=managed'
      - '--no-allow-unauthenticated'
      - '--service-account=agent-runner-sa@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-env-vars=GCP_PROJECT_ID=${PROJECT_ID},DULCE_AGENTS_TOPIC=${_DULCE_AGENTS_TOPIC},DULCE_AGENT_RUNS_TABLE=${_DULCE_AGENT_RUNS_TABLE}'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api'
    args:
      - 'run'
      - 'deploy'
      - 'dulce-api'
      - '--project=${PROJECT_ID}'
      - '--region=${_GCP_REGION}'
      - '--image=${_ARTIFACT_REGISTRY}/${PROJECT_ID}/dulce/api:${_GITHUB_SHA}'
      - '--platform=managed'
      - '--allow-unauthenticated'

substitutions:
  _ARTIFACT_REGISTRY: 'asia-southeast1-docker.pkg.dev'
  _GCP_REGION: 'asia-southeast1'
  _DULCE_AGENTS_TOPIC: 'dulce.agents'
  _DULCE_AGENT_RUNS_TABLE: 'dulce_agent_runs'

images:
  - '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/dulce/agent-runner:${_GITHUB_SHA}'
  - '${_ARTIFACT_REGISTRY}/${PROJECT_ID}/dulce/api:${_GITHUB_SHA}'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY