permissions:
  contents: read
name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_DAEMON: false
  HUSKY: 0

jobs:
  setup:
    name: Setup & Install
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      affected-projects: ${{ steps.affected.outputs.projects }}
      has-affected: ${{ steps.affected.outputs.has-affected }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true
      - name: Set Nx base/head SHAs
        uses: nrwl/nx-set-shas@v4
      - id: affected
        name: Determine affected projects
        shell: bash
        run: |
          set -euo pipefail
          projects=$(pnpm exec nx print-affected --select=projects || true)
          if [ -z "$projects" ]; then
            echo "projects=" >> "$GITHUB_OUTPUT"
            echo "has-affected=false" >> "$GITHUB_OUTPUT"
          else
            echo "projects=$projects" >> "$GITHUB_OUTPUT"
            echo "has-affected=true" >> "$GITHUB_OUTPUT"
          fi

steps:
  - uses: actions/checkout@v4
    with:
      fetch-depth: 0
  - uses: actions/setup-node@v4
    with:
      node-version: ${{ env.NODE_VERSION }}
      cache: pnpm
  - uses: pnpm/action-setup@v4
    with:
      version: ${{ env.PNPM_VERSION }}
      run_install: false
  - name: Install Dependencies
    run: |
      pnpm install
  - name: Run Tests
    run: |
      pnpm test