name: Dependency Review

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3.1.4
        with:
          fail-on-severity: high
          deny-licenses: GPL-3.0, AGPL-3.0
