name: ADK CI/CD

on:
  push:
    paths:
      - 'adk/**'
      - '.github/workflows/adk-ci-cd.yml'
  pull_request:
    paths:
      - 'adk/**'
      - '.github/workflows/adk-ci-cd.yml'

jobs:
  lint-test-build:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: cd adk && pnpm lint

      - name: Test
        run: cd adk && pnpm test

      - name: Build
        run: cd adk && tsc

  codacy-analysis:
    name: Codacy Analysis
    runs-on: ubuntu-latest
    needs: lint-test-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@master
        with:
          directory: adk
          format: sarif
          output: results.sarif
          
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
