name: AI Models Validation

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/agents/**'
      - 'libs/agents/**'
      - 'infra/terraform/vertex-agents/**'
  workflow_dispatch:

jobs:
  validate-ai-models:
    name: Validate AI Models and Agents
    runs-on: ubuntu-latest
    env:
      STORE_PATH: ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.0.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --frozen-lockfile

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2.1.2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2.1.0

      - name: Run agent validation tests
        run: |
          echo "Running AI model validation tests..."
          # Execute tests specific to AI agent functionality
          pnpm nx test agents

      - name: Run agent integration tests
        run: |
          echo "Running AI agent integration tests..."
          # Execute integration tests against a test environment
          # pnpm nx run agents:integration-test

      - name: Validate agent configurations
        run: |
          echo "Validating agent configurations..."
          # Verify that agent configurations are valid
          # This could be a custom script that validates config files
          # node scripts/validate-agent-configs.js
