name: Codacy Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  codacy-analysis:
    name: Codacy Static Analysis
    runs-on: ubuntu-latest
    env:
      STORE_PATH: $(pnpm store path)
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@c4c9e84c7b9465a335b762113626741ec8e95c00 # v4.0.1
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@b8c4212bc8178b24a6daf5e3da8ac9dd35e3bab9 # v4.0.2
        with:
          version: 8
          run_install: false
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --frozen-lockfile
        
      - name: Run Codacy Analysis
        run: |
          echo "Running Codacy local analysis..."
          chmod +x ./.codacy/cli.sh
          ./.codacy/cli.sh analyze --format sarif > codacy-results.sarif
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@5b6282e9b4faa8b74e62906ca462e4fdffe9e1a2 # v3.25.6
        with:
          sarif_file: codacy-results.sarif
          category: codacy-analysis
