name: Database Migration Verification

on:
  pull_request:
    branches: [main, develop]
    paths:
      - '**/migrations/**'
      - '**/schemas/**'
      - 'infra/terraform/bigquery/**'

jobs:
  verify-migrations:
    name: Verify Database Migrations
    runs-on: ubuntu-latest
    env:
      STORE_PATH: ''
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f42bc1c9890d4047f6d0ff69e889a4ca # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.0.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4 # v4
        with:
          path: |
            ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Node.js
        uses: actions/setup-node@b4ffde65f42bc1c9890d4047f6d0ff69e889a4ca # v4
        with:
          node-version: '20'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2.1.2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2.1.0

      - name: Verify migrations
        run: |
          echo "Verifying database migrations..."
          # Example: Run a script that verifies migrations against a test DB
          # pnpm run migrations:verify
