name: Database Migration Verification

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/migrations/**'
      - '**/schemas/**'
      - 'infra/terraform/bigquery/**'

jobs:
  verify-migrations:
    name: Verify Database Migrations
    runs-on: ubuntu-latest
    env:
      STORE_PATH: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.0.0
          run_install: false

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Authenticate to GCP
        uses: google-github-actions/auth@55bd3a7c6e2ae7e6884bfe4c7bf685fe519a5a36 # v2.1.2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@e2ab1afc8b16a89a5bc7eac718364352c9ebb8d6 # v2.1.0

      - name: Verify migrations
        run: |
          echo "Verifying database migrations..."
          # Example: Run a script that verifies migrations against a test DB
          # pnpm run migrations:verify
