name: Database Migration Verification

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/migrations/**'
      - '**/schemas/**'
      - 'infra/terraform/bigquery/**'

jobs:
  verify-migrations:
    name: Verify Database Migrations
    runs-on: ubuntu-latest
    env:
      STORE_PATH: $(pnpm store path)
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@c4c9e84c7b9465a335b762113626741ec8e95c00 # v4.0.1
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@8095b2b9580c96f4e9a8177bec82d79210851024 # v4.0.0
        with:
          version: 8
          run_install: false
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --frozen-lockfile

      - name: Authenticate to GCP
        uses: google-github-actions/auth@55bd3a7c6e2ae7e6884bfe4c7bf685fe519a5a36 # v2.1.2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}

      - name: Setup pnpm cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: |
            ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@e2ab1afc8b16a89a5bc7eac718364352c9ebb8d6 # v2.1.0

      - name: Verify migrations
        run: |
          echo "Verifying database migrations..."
          # Example: Run a script that verifies migrations against a test DB
          # pnpm run migrations:verify
