# GitHub Actions CI/CD Workflow for Dulce de Saigon
#
# This workflow orchestrates the entire CI/CD process, from code validation
# to deployment on Google Cloud Platform. It is designed to be secure,
# efficient, and compliant with Vietnamese data protection regulations.
#
# Key Features:
# - Secure Authentication: Uses Google Cloud's Workload Identity Federation (WIF)
#   to authenticate without service account keys.
# - Pull Request Trigger: The workflow runs automatically on every pull request
#   targeting the 'main' branch, ensuring all changes are validated.
# - Efficient Execution: Leverages Nx 'affected' commands to only run tests
#   and builds for the projects impacted by the changes.
# - Cloud Build Integration: Delegates the heavy lifting of building and deploying
#   to Google Cloud Build, which is optimized for the GCP environment.

name: 'GitOps CI/CD Pipeline'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    name: 'Build, Test, and Deploy'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up gcloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Set up Node.js and pnpm'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: 'Install Dependencies'
        run: pnpm install --frozen-lockfile

      - name: 'Derive SHAs'
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "NX_BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
            echo "NX_HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          else
            echo "NX_BASE=${{ github.event.before }}" >> $GITHUB_ENV
            echo "NX_HEAD=${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: 'Run Linting'
        run: npx pnpm nx affected --target=lint --base=$NX_BASE --head=$NX_HEAD

      - name: 'Run Tests'
        run: npx pnpm nx affected --target=test --base=$NX_BASE --head=$NX_HEAD

      - name: 'Submit to Google Cloud Build'
        run: |
          gcloud builds submit --config cloudbuild.yaml . \
            --substitutions=_SHORT_SHA=${{ github.sha }}
