name: Localization Validation

on:
  push:
    branches: [main, develop]
    paths:
      - '**/locales/**'
      - '**/translations/**'
      - '**/i18n/**'
  pull_request:
    branches: [main, develop]
    paths:
      - '**/locales/**'
      - '**/translations/**'
      - '**/i18n/**'

jobs:
  validate-translations:
    name: Validate Translation Files
    runs-on: ubuntu-latest
    env:
      STORE_PATH: ''
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f42bc1c9890d4047f6d0ff69e889a4ca # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@4fe8674f344d65cf7384fc21ba97c2b05fd8df75 # v4.1.0
        with:
          version: 8.6.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v4
        with:
          path: |
            ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Node.js
        uses: actions/setup-node@b4ffde65f42bc1c9890d4047f6d0ff69e889a4ca # v4
        with:
          node-version: '20'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run translation validation
        run: |
          # Run your custom script for validating Vietnamese encoding
          pnpm exec node scripts/validate-encoding.js

          # Run your Vietnamese test script
          pnpm exec node scripts/test-vietnamese.js

      - name: Check for missing translations
        run: |
          # Add your custom script to check for missing translations across locales
          echo "Checking for missing translations..."
          # Example command (replace with your actual check)
          # pnpm run i18n:check-missing
