name: NX Cloud Cache Warming

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight every Sunday

jobs:
  nx-cache-warming:
    name: Warm NX Cloud Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: NX Cloud Warm Cache - Build
        run: pnpm nx run-many --target=build --all --parallel=5
        
      - name: NX Cloud Warm Cache - Lint
        run: pnpm nx run-many --target=lint --all --parallel=5
        
      - name: NX Cloud Warm Cache - Test
        run: pnpm nx run-many --target=test --all --parallel=5
