name: NX Monorepo Validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    name: Validate NX Monorepo
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile
          bash tools/scripts/install-tool-dependencies.sh
      
      - name: Run TypeScript validation
        run: npx ts-node tools/scripts/check-typescript-issues.ts
      
      - name: Analyze dependencies
        run: npx ts-node tools/scripts/analyze-dependencies.ts
      
      - name: Run NX affected commands
        run: |
          npx nx affected --target=lint
          npx nx affected --target=test
          npx nx affected --target=build
      
      - name: Upload validation reports
        uses: actions/upload-artifact@v3
        with:
          name: validation-reports
          path: |
            typescript-issues.json
            dependency-issues.json
