name: PR Validation & Quality Gate

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

permissions:
  contents: read
  pull-requests: write
  security-events: write
  checks: write
  statuses: write

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  #