---
name: PR Agent

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  pull-requests: write
  issues: write  # Required for adding labels to PRs

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run PR Agent on PR
    steps:
      - name: PR Agent action
        uses: Codium-ai/pr-agent@8d382f8c7df4f391e2e55d6f834843a6dde3d7a2 # v0.11
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
