name: PR-Agent

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  pull-requests: write
  issues: write  # Required for adding labels to PRs

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    if: github.event_name != 'issue_comment' || github.event.issue.pull_request
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.0.0
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install
          
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get secrets from Google Cloud Secret Manager
        run: |
          echo "OPENAI_KEY=$(gcloud secrets versions access latest --secret=OPENAI_KEY)" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=$(gcloud secrets versions access latest --secret=github-token)" >> $GITHUB_ENV
          
      - name: PR Agent Action
        uses: Codium-ai/pr-agent@v0.11
        env:
          OPENAI_KEY: ${{ env.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
