name: Mark and Close Stale PRs

on:
  schedule:
    - cron: '30 1 * * *'  # Run at 1:30 AM every day

jobs:
  stale:
    name: Mark Stale PRs
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This pull request has been inactive for 14 days and is being marked as stale. It will be closed in 7 days if no further activity occurs.'
          close-pr-message: 'This pull request was closed because it has been stale for 7 days with no activity. Feel free to reopen if you want to work on this again.'
          days-before-pr-stale: 14
          days-before-pr-close: 7
          stale-pr-label: 'stale'
          exempt-pr-labels: 'no-stale,keep-open,dependencies'
          operations-per-run: 100
